orbs:
  python: circleci/python@2.0.1

workflows:
    example-workflow:
      jobs:
        - python/test:
            fail-if-missing-tool: true 
            pip-dependency-file: pip install -U -r re*/st*/optional-requirements.txt 
            pre-install-steps: pip install -U -r requirements.txt 
            setup: bash startup 
