name: blacked.cum

on: push

jobs:
  PEP8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install black
        run: |
          pip install black isort autoflake
      - name: lint with isort and black
        run: |
          black plugins/* assistant/*
          isort plugins/* assistant/*
          autoflake --in-place --remove-unused-variables plugins/*
          autoflake --in-place --remove-unused-variables assistant/*
      # commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Pehli Fursat m nikal'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Me Buddhhu 
          commit_user_email: buddhhu@ultroid.tech

